//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_factura_electronica
    {
        public int id { get; set; }
        public string TipoIdentificacion { get; set; }
        public string Identificacion { get; set; }
        public string NombreComercial { get; set; }
        public string CodigoPais { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public string Barrio { get; set; }
        public string OtrasSenas { get; set; }
        public string UsuarioATV { get; set; }
        public string ClaveATV { get; set; }
        public string ClaveCertificado { get; set; }
        public string Normativa { get; set; }
        public string FechaResolucion { get; set; }
        public string Surcusal { get; set; }
        public Nullable<int> Consecutivo { get; set; }
        public string UrlBase { get; set; }
        public string UrlEnvio { get; set; }
        public string UrlComprobantes { get; set; }
        public string NombreCompleto { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Aplica { get; set; }
        public string Impresora { get; set; }
        public Nullable<int> Nota { get; set; }
        public string Terminal { get; set; }
        public string CorreoEnvio { get; set; }
    }
}
