//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public int idCategoría { get; set; }
        public int tipoCategoría { get; set; }
        public string descripción { get; set; }
        public double costo { get; set; }
        public string abreviación { get; set; }
        public int estado { get; set; }
    }
}
