CREATE TABLE [dbo].[admin_factura_electronica] (
    [id]                 INT           IDENTITY (1, 1) NOT NULL,
    [TipoIdentificacion] VARCHAR (50)  NULL,
    [Identificacion]     VARCHAR (50)  NULL,
    [NombreComercial]    VARCHAR (50)  NULL,
    [CodigoPais]         VARCHAR (50)  NULL,
    [Provincia]          VARCHAR (2)   NULL,
    [Canton]             VARCHAR (2)   NULL,
    [Distrito]           VARCHAR (2)   NULL,
    [Barrio]             VARCHAR (2)   NULL,
    [OtrasSenas]         VARCHAR (300) NULL,
    [UsuarioATV]         VARCHAR (300) NULL,
    [ClaveATV]           VARCHAR (300) NULL,
    [ClaveCertificado]   VARCHAR (300) NULL,
    [Normativa]          VARCHAR (150) NULL,
    [FechaResolucion]    VARCHAR (50)  NULL,
    [Surcusal]           VARCHAR (10)  NULL,
    [Consecutivo]        INT           NULL,
    [UrlBase]            VARCHAR (350) NOT NULL,
    [UrlEnvio]           VARCHAR (350) NULL,
    [UrlComprobantes]    VARCHAR (350) NULL,
    [NombreCompleto]     VARCHAR (350) NULL,
    [Telefono]           VARCHAR (350) NULL,
    [Correo]             VARCHAR (150) NULL,
    [Aplica]             INT           NULL,
    [Impresora]          VARCHAR (300) NULL,
    [Nota]               INT           NULL,
    [Terminal]           VARCHAR (10)  NULL,
    [CorreoEnvio]        VARCHAR (150) NULL,
    CONSTRAINT [PK_admin_factura_electronica] PRIMARY KEY CLUSTERED ([id] ASC)
);

